### ISSUE TITLE
Occationally panic on jiffy mpsc node

### ISSUE THREAD

**Issue by testforvln99** [Lol3rrr/nolock#2]
I wrote a demo with the jiffy mpsc module on Win10. Mostly it wen well but I came across once with panic info:

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\testuser\.cargo\registry\src\mirrors.ustc.edu.cn-15f9db60536bad60\nolock-0.4.0\src\queues\mpsc\jiffy\node.rs:93:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I read the function comments and found that the unwrap() function is meant to be safe.  Would there be any bug in it?

My test code is below:

```
use std::thread;
use std::time::{Duration, Instant};
use core_affinity::{CoreId, get_core_ids};
use polars::prelude::{DataFrame, NamedFromOwned, Series};

fn main() {
    loop {
        let (mut receiver, mut sender) = nolock::queues::mpsc::jiffy::queue::<Instant>();
        let times = 10000;
        let times_clone = times.clone();

        let receiver = thread::spawn(move || {
            core_affinity::set_for_current(CoreId { id: 3 });
            let mut num = 0;
            let mut sum_latency = 0.0;
            let mut latencies = vec![];
            for idx in 0..times_clone {
                if let Some(info) = receiver.dequeue() {
                    let a = info.elapsed().as_secs_f64();
                    latencies.push(a);
                }
            }
            let series = Series::from_vec("", latencies);
            let df = DataFrame::new(vec![series]).unwrap();
            println!("{:?}", df.describe(None));
        });

        thread::spawn(move || {
            core_affinity::set_for_current(CoreId { id: 4 });
            for idx in 0..times {
                thread::sleep(Duration::from_millis(1));
                let start = Instant::now();
                sender.enqueue(start);
            }
        });
        receiver.join();
    }
}
```

**Comment by Lol3rrr** [comment]
Thanks for the bug report. I will investigate this issue later today and will see what I can find

**Comment by testforvln99** [comment]
FYI, I ran this code for 3 hours and the panic problem occured 6 times. So you may try run this for longer time.

**Comment by testforvln99** [comment]
Furthermore, when I ran the test code today after eliminating the core_affinity::set_for_current functions, the panic still occured.

**Comment by testforvln99** [comment]
I tested the program without core_affinity::set_for_current functions, the panic problem still occursed.
CentOS Linux release 7.8.2003 (Core)   rustc 1.60.0 (7737e0b5c 2022-04-04)

**Comment by Lol3rrr** [comment]
Hey, I just pushed a minor attempted fix for the Issue. If you want you can test it now as a git dependency and I will also try to find a good way to test this issue to verify that it was actually fixed or not

**Comment by testforvln99** [comment]
I tested the new commit and found no panic at all during my test! I think this commit more strict than my pr.

**Comment by Lol3rrr** [comment]
yeah, the invariants oultined in the code, weren't exactly held up before.
